import { z } from "zod";
import type { CreateOrderInput } from "./repositories";

export const createOrderRequestSchema = z.object({
  status: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  phone: z.string().optional(),
  phone2: z.string().optional(),
  address: z.string().optional(),
  commune: z.string().optional(),
  wilaya: z.string().optional(),
  channel: z.string().optional(),
  comment: z.string().optional(),
  objective: z.string().optional(),
  delivery_company: z.string().optional(),
  delivery_fees: z.number().optional(),
  delivery_notes: z.number().optional(),
  delivery_attempt: z.number().optional(),
  tracking_id: z.string().optional(),
  tracker_id: z.number().optional(),
  dc_recent_status: z.string().optional(),
  yalidine_status: z.string().optional(),
  agent_id: z.number().optional(),
  partner_id: z.number().optional(),
  product: z.string().optional(),
  product_color: z.string().optional(),
  product_size: z.string().optional(),
  product_price: z.number().optional(),
  product_qty: z.number().min(1),
  shipping_price: z.number().optional(),
  is_auto_delivered: z.boolean().optional().default(false),
  is_exchange_required: z.boolean().optional().default(false),
  is_exchange: z.boolean().optional(),
  has_exchange: z.boolean().optional(),
  has_defect: z.boolean().optional().default(false),
  is_free_shipping: z.boolean().optional(),
  is_stopdesk: z.boolean().optional(),
  is_wholesale: z.boolean().optional(),
  return_processed: z.boolean().optional().default(false),
  stopdesk: z.string().optional(),
});

