-- Migration: Create partner commissions snapshot table
-- Purpose: Lock commission amount at order creation time so later product rate
--          changes do not rewrite unpaid affiliate earnings (COD delivery can take days).

CREATE TABLE IF NOT EXISTS commissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT NOT NULL REFERENCES partners(id),
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_commission NUMERIC(12, 2) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT commissions_quantity_positive CHECK (quantity > 0),
  CONSTRAINT commissions_amount_non_negative CHECK (amount >= 0),
  CONSTRAINT commissions_unit_commission_non_negative CHECK (unit_commission >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_commissions_order_id_unique
  ON commissions(order_id);

CREATE INDEX IF NOT EXISTS idx_commissions_partner_id
  ON commissions(partner_id);

CREATE INDEX IF NOT EXISTS idx_commissions_partner_created_at
  ON commissions(partner_id, created_at DESC);

COMMENT ON TABLE commissions IS
  'Snapshot of affiliate commission locked when the order is created';
COMMENT ON COLUMN commissions.unit_commission IS
  'Per-unit commission (DZD) copied from products.retail_commission at order time';
COMMENT ON COLUMN commissions.amount IS
  'Total commission locked at order time: unit_commission * quantity';
