-- Migration: Bellami Stores schema
-- Purpose: Supplier stores identity, product ownership, supplier price snapshots,
--          return batches, and supplier payment settlements.
-- Also seeds default store id=1 so store_id FKs are never null.

-- ---------------------------------------------------------------------------
-- stores
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  fullname TEXT,
  username TEXT,
  avatar TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stores_email ON stores (email);
CREATE INDEX IF NOT EXISTS idx_stores_status ON stores (status);

COMMENT ON TABLE stores IS
  'Supplier store identity (1 Clerk user ≈ 1 store). Row id=1 is the default fallback store.';

-- Default store (#1): prevents NULL / FK violations when adding store_id columns
INSERT INTO stores (id, email, fullname, username, status)
VALUES (1, 'admin@bellami.fashion', 'Bellami Store', 'bellami', 'active')
ON CONFLICT (id) DO NOTHING;

-- Keep identity sequence in sync after explicit id=1 insert
SELECT setval(
  pg_get_serial_sequence('stores', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM stores), 1)
);

-- ---------------------------------------------------------------------------
-- products: ownership + supplier cost
-- ---------------------------------------------------------------------------
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS store_id BIGINT DEFAULT 1 REFERENCES stores(id),
  ADD COLUMN IF NOT EXISTS supplier_price NUMERIC(12, 2);

UPDATE products SET store_id = 1 WHERE store_id IS NULL;

ALTER TABLE products
  ALTER COLUMN store_id SET DEFAULT 1,
  ALTER COLUMN store_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_products_store_id ON products (store_id);

COMMENT ON COLUMN products.store_id IS
  'Owning store; each product belongs to one store. Defaults to store #1.';
COMMENT ON COLUMN products.supplier_price IS
  'Amount Bellami pays the supplier per unit when order is delivered';

-- ---------------------------------------------------------------------------
-- orders: store scope + payment flag
-- ---------------------------------------------------------------------------
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS store_id BIGINT DEFAULT 1 REFERENCES stores(id),
  ADD COLUMN IF NOT EXISTS is_supplier_paid BOOLEAN NOT NULL DEFAULT false;

UPDATE orders SET store_id = 1 WHERE store_id IS NULL;

ALTER TABLE orders
  ALTER COLUMN store_id SET DEFAULT 1,
  ALTER COLUMN store_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_store_id ON orders (store_id);
CREATE INDEX IF NOT EXISTS idx_orders_store_status ON orders (store_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_store_supplier_paid
  ON orders (store_id, is_supplier_paid)
  WHERE status = 'delivered';

COMMENT ON COLUMN orders.store_id IS
  'Store that owns the product fulfilled on this order. Defaults to store #1.';
COMMENT ON COLUMN orders.is_supplier_paid IS
  'True once the order is included in a supplier payment batch';

-- ---------------------------------------------------------------------------
-- order_item: snapshot supplier price at create time
-- ---------------------------------------------------------------------------
ALTER TABLE order_item
  ADD COLUMN IF NOT EXISTS unit_supplier_price NUMERIC(12, 2);

COMMENT ON COLUMN order_item.unit_supplier_price IS
  'Per-unit supplier_price copied from products at order creation';

-- ---------------------------------------------------------------------------
-- returns (1 return batch → many orders)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  status TEXT NOT NULL DEFAULT 'processed'
    CHECK (status IN ('processed', 'collected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_returns_store_id ON returns (store_id);
CREATE INDEX IF NOT EXISTS idx_returns_store_status ON returns (store_id, status);

COMMENT ON TABLE returns IS
  'Bellami-created batch of returned parcels for a store';

CREATE TABLE IF NOT EXISTS return_orders (
  return_id BIGINT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  PRIMARY KEY (return_id, order_id),
  CONSTRAINT return_orders_order_id_unique UNIQUE (order_id)
);

CREATE INDEX IF NOT EXISTS idx_return_orders_return_id ON return_orders (return_id);

COMMENT ON TABLE return_orders IS
  'Orders included in a return batch (one order ∈ at most one return)';

-- ---------------------------------------------------------------------------
-- payments (supplier settlements)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0
    CHECK (amount >= 0),
  is_paid BOOLEAN NOT NULL DEFAULT false,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_payments_store_id ON payments (store_id);
CREATE INDEX IF NOT EXISTS idx_payments_store_is_paid ON payments (store_id, is_paid);

COMMENT ON TABLE payments IS
  'Supplier payment batch: is_paid=false (ready), is_paid=true (paid)';

CREATE TABLE IF NOT EXISTS payment_orders (
  payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0
    CHECK (amount >= 0),
  PRIMARY KEY (payment_id, order_id),
  CONSTRAINT payment_orders_order_id_unique UNIQUE (order_id)
);

CREATE INDEX IF NOT EXISTS idx_payment_orders_payment_id ON payment_orders (payment_id);

COMMENT ON TABLE payment_orders IS
  'Orders included in a payment; amount is Σ(unit_supplier_price × qty) snapshot';
