-- Migration: store_assignments
-- Links a user email to the stores they can operate (stores_manager role).
-- Role stays in auth provider metadata; this table is assignment only.
-- Email matches stores.email as the portable identity key.

CREATE TABLE IF NOT EXISTS store_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT store_assignments_email_store_unique UNIQUE (email, store_id)
);

CREATE INDEX IF NOT EXISTS idx_store_assignments_email
  ON store_assignments (email);

CREATE INDEX IF NOT EXISTS idx_store_assignments_store_id
  ON store_assignments (store_id);

COMMENT ON TABLE store_assignments IS
  'Which stores an email is assigned to operate. Role is not stored here.';
COMMENT ON COLUMN store_assignments.email IS
  'Normalized user email (lowercase). Same identity key as stores.email.';
