-- If an earlier 045 created store_managers (clerk_user_id), replace it.
-- Also creates store_assignments for databases that already applied the old 045.

DROP TABLE IF EXISTS store_managers;

CREATE TABLE IF NOT EXISTS store_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT store_assignments_email_store_unique UNIQUE (email, store_id)
);

CREATE INDEX IF NOT EXISTS idx_store_assignments_email
  ON store_assignments (email);

CREATE INDEX IF NOT EXISTS idx_store_assignments_store_id
  ON store_assignments (store_id);
